#!/bin/bash
pip install -i https://test.pypi.org/simple/ widget-periodictable
pip install -i https://test.pypi.org/simple/ voila-osscar-template==0.0.1 
jupyter labextension install @jupyter-widgets/jupyterlab-manager
#jupyter nbextension      enable --py --sys-prefix appmode
#jupyter serverextension  enable --py --sys-prefix appmode
jupyter nbextension      enable --py widgetsnbextension

#cp -r osscar /srv/conda/envs/notebook/share/jupyter/voila/templates/. 
